"""add borrows and refactor users

Revision ID: 97455443beeb
Revises: 81565c3be76d
Create Date: 2025-03-11 19:05:00.655851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97455443beeb"
down_revision: Union[str, None] = "81565c3be76d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("borrowed_books_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "borrowed_books_count")
    # ### end Alembic commands ###
